name: Update Iceberg Image

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/entries.json'
      - 'src/ai_iceberg.py'

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Pillow>=10.0.0"

      - name: Generate iceberg image
        run: python src/ai_iceberg.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet images/iceberg.png || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images/iceberg.png
          git commit -m "Update iceberg image"
          git push 